// generation-worker — Sprint B4. Invoked by pg_cron (via pg_net, service-role
// bearer token) with one queue message at a time. Not browser-facing.
import { json } from "../_shared/http.ts";
import { serviceClient } from "../_shared/clients.ts";
import { gemini, MODELS } from "../_shared/gemini.ts";
import { generateJson, type Part } from "../_shared/generate.ts";
import { assetGenerationSchema } from "../_shared/schemas.ts";

interface JobMessage {
  jobId?: string;
  workspaceId?: string;
  campaignId?: string;
  ideaId?: string;
  format?: string;
  regenerationModifier?: string; // Optional: "premium", "viral", "educational", etc.
}
interface Payload {
  msg_id?: number;
  message?: JobMessage;
}

Deno.serve(async (req) => {
  let payload: Payload;
  try {
    payload = (await req.json()) as Payload;
  } catch {
    return json({ error: "invalid JSON body" }, 400);
  }

  const { message, msg_id } = payload;
  if (!message?.jobId) return json({ error: "message.jobId is required" }, 400);

  const svc = serviceClient();
  try {
    await svc.from("generation_jobs").update({ status: "running" }).eq("id", message.jobId);

    // 1. Load context: idea, campaign, product dossier
    const { data: idea, error: ideaError } = await svc
      .from("campaign_ideas")
      .select("*, campaigns(*, products(*))")
      .eq("id", message.ideaId)
      .single();

    if (ideaError || !idea) throw new Error(`Idea not found: ${ideaError?.message}`);

    const campaign = idea.campaigns;
    const product = campaign.products;
    const dossier = product.dossier;

    // 2. Generate Image with Nano Banana 2 (gemini-3.1-flash-image) via the
    // Interactions API — image models are NOT accessed through
    // models.generateContent. aspect_ratio/image_size live under
    // response_format (image_config under generation_config was removed in
    // the May 2026 breaking change).
    const imagePrompt = buildImagePrompt(idea, dossier, product, message.regenerationModifier);
    const interaction = await gemini().interactions.create({
      model: MODELS.image,
      input: imagePrompt,
      response_format: {
        type: "image",
        aspect_ratio: idea.format === "story" ? "9:16" : "1:1",
      },
    });

    const imagePart = interaction.output_image
      ? { data: interaction.output_image.data, mimeType: "image/png" }
      : null;

    if (!imagePart) throw new Error("No image was generated by the model");

    // 3. Generate Copy and strategic scores with gemini-3.5-flash
    const copyPrompt = buildCopyPrompt(idea, dossier, campaign, message.regenerationModifier);
    const generationData = await generateJson(gemini(), [{ text: copyPrompt }], assetGenerationSchema);

    // 4. Upload Image to Storage
    const assetId = crypto.randomUUID();
    const storagePath = `${message.workspaceId}/${assetId}.png`;
    const imageBytes = Uint8Array.from(atob(imagePart.data), (c) => c.charCodeAt(0));

    const { error: uploadError } = await svc.storage
      .from("generated")
      .upload(storagePath, imageBytes, {
        contentType: imagePart.mimeType || "image/png",
      });

    if (uploadError) throw uploadError;

    // 5. Insert Asset row
    const { error: assetError } = await svc.from("assets").insert({
      id: assetId,
      workspace_id: message.workspaceId,
      campaign_id: message.campaignId,
      idea_id: message.ideaId,
      name: idea.title,
      type: idea.format,
      platform: idea.platforms[0], // Primary platform
      storage_path: storagePath,
      copy_caption: generationData.caption,
      copy_hashtags: generationData.hashtags,
      performance_score: generationData.performanceScore,
      brand_fit_score: generationData.brandFitScore,
      strategic_rationale: generationData.strategicRationale,
      status: "pending-review",
    });

    if (assetError) throw assetError;

    // 6. Finalize Job and Queue
    await svc
      .from("generation_jobs")
      .update({ status: "succeeded", finished_at: new Date().toISOString() })
      .eq("id", message.jobId);

    // Ack the queue
    if (msg_id) {
      await svc.rpc("pgmq_delete", { queue_name: "generation_jobs", msg_id });
    }

    // 7. Increment credits (simplified)
    await svc.rpc("increment_workspace_credits", { ws_id: message.workspaceId, amount: 1 });

    return json({ ok: true, assetId });
  } catch (err) {
    console.error("generation-worker failed", err);
    await svc
      .from("generation_jobs")
      .update({
        status: "failed",
        error: String(err).slice(0, 500),
        finished_at: new Date().toISOString(),
      })
      .eq("id", message.jobId);
    return json({ error: String(err) }, 500);
  }
});

function buildImagePrompt(
  idea: any,
  dossier: any,
  product: any,
  modifier?: string,
): string {
  const base = [
    "You are a high-end commercial photographer and digital artist.",
    `Product: ${product.name}.`,
    `Creative Direction: ${idea.creative_direction}.`,
    `Brand Aesthetic: ${dossier.aestheticTag}.`,
    `Color Palette: ${dossier.colors.join(", ")}.`,
    `Format: ${idea.format}.`,
  ];

  if (modifier === "premium") {
    base.push("Style: Ultra-premium, luxurious, high-contrast, minimalist studio setting.");
  } else if (modifier === "viral") {
    base.push("Style: Dynamic, high-energy, eye-catching, trendy, vibrant colors.");
  } else if (modifier === "educational") {
    base.push("Style: Clean, informative, clear focus on product features, soft lighting.");
  }

  base.push("Output: A single high-quality, professional marketing image following these constraints.");
  return base.join("\n");
}

function buildCopyPrompt(
  idea: any,
  dossier: any,
  campaign: any,
  modifier?: string,
): string {
  return [
    "You are a conversion-focused copywriter and marketing strategist.",
    `Brand voice: ${dossier.voiceSummary}.`,
    `Brand archetype: ${dossier.brandArchetype}.`,
    `Campaign objective: ${campaign.strategy?.objective}.`,
    `Content pillar: ${idea.content_pillar}.`,
    `Target audience: ${campaign.strategy?.targetAudienceSegment}.`,
    `Idea title: ${idea.title}.`,
    `Idea description: ${idea.description}.`,
    `Platform: ${idea.platforms[0]}.`,
    modifier ? `Regeneration modifier: ${modifier}.` : "",
    "",
    "Generate high-converting copy including a caption, hashtags, and a clear call-to-action.",
    "Also, provide a performance score (0-100) and a brand fit score (0-100) based on your strategic assessment.",
    "Finally, provide a brief, user-friendly strategic rationale for why this asset works for the campaign.",
    "Return ONLY JSON matching the required schema.",
  ].join("\n");
}
